#include <iostream>

int main() {

	/*
	PROBLEM NUMBER : 2

	PROBLEM TITLE : " Even Fibonacci numbers "

	PROBLEM STATEMENT : " Each new term in the Fibonacci
	sequence is generated by adding
	the previous two terms.By starting
	with 1 and 2, the first 10 terms
	will be :

	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the
	Fibonacci sequence whose values
	do not exceed four million, find
	the sum of the even - valued terms."

	SOLUTION : " 4613732 "

	*/

	// Initiate the sequence, according to the above definition.
	int prev1 = 1;
	int prev2 = 2;

	// curr is the current fibonnaci number that we are inspecting
	// and testing for evenness.
	int curr = 2;
	int sum = 0;

	// For as long as the terms are less than 4000000...
	for (; curr < 4000000; ) {

		// If the number is even, then add it to the sum
		if (curr % 2 == 0) {
			sum = curr + sum;
		}

		// Progress the sequence.
		curr = prev1 + prev2;
		prev1 = prev2;
		prev2 = curr;

	}

	std::cout << sum;

	return 0;
}

/* Notes:

- N/A

*/